spring:
    datasource:
        url: jdbc:postgresql://raja.db.elephantsql.com:5432/ngnuzplg
        username: ngnuzplg
        password: 0dBYH_JmdGiQhoYp7sebDvAy0pnLkz6k
        hikari:
            maximum-pool-size: 2 
    jpa:
        show-sql: true
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect